language: node_js
node_js:
  - "6"
install:
  - npm install -g npm
  - npm install -g coveralls
  - npm install

script:
  - npm test
  - npm run lint
#  - npm run coverage
#  - coveralls < ./coverage/lcov.info || true # ignore coveralls error

# Allow Travis tests to run in containers.
sudo: false

deploy:
  provider: npm
  email: tally.barak@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    all_branches: true
